// This file is auto-generated by the Supabase CLI.
// It represents the public schema of your database.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      _prisma_migrations: {
        Row: {
          applied_steps_count: number
          checksum: string
          finished_at: string | null
          id: string
          logs: string | null
          migration_name: string
          rolled_back_at: string | null
          started_at: string
        }
        Insert: {
          applied_steps_count?: number
          checksum: string
          finished_at?: string | null
          id: string
          logs?: string | null
          migration_name: string
          rolled_back_at?: string | null
          started_at?: string
        }
        Update: {
          applied_steps_count?: number
          checksum?: string
          finished_at?: string | null
          id?: string
          logs?: string | null
          migration_name?: string
          rolled_back_at?: string | null
          started_at?: string
        }
        Relationships: []
      }
      experiences: {
        Row: {
          company: string
          created_at: string
          description: string
          display_order: number
          duration: string
          id: string
          position: string
          updated_at: string
        }
        Insert: {
          company: string
          created_at?: string
          description: string
          display_order: number
          duration: string
          id?: string
          position: string
          updated_at?: string
        }
        Update: {
          company?: string
          created_at?: string
          description?: string
          display_order?: number
          duration?: string
          id?: string
          position?: string
          updated_at?: string
        }
        Relationships: []
      }
      portfolio_items: {
        Row: {
          author_id: string | null
          challenge: string
          created_at: string
          description: string
          id: string
          image_hint: string
          image_url: string
          live_url: string | null
          repo_url: string | null
          results: string
          solution: string
          tags: string[]
          title: string
          updated_at: string
        }
        Insert: {
          author_id?: string | null
          challenge: string
          created_at?: string
          description: string
          id?: string
          image_hint: string
          image_url: string
          live_url?: string | null
          repo_url?: string | null
          results: string
          solution: string
          tags: string[]
          title: string
          updated_at?: string
        }
        Update: {
          author_id?: string | null
          challenge?: string
          created_at?: string
          description?: string
          id?: string
          image_hint?: string
          image_url?: string
          live_url?: string | null
          repo_url?: string | null
          results?: string
          solution?: string
          tags?: string[]
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "portfolio_items_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          bio: string
          created_at: string
          email: string
          id: string
          image_url: string
          name: string
          updated_at: string
        }
        Insert: {
          bio: string
          created_at?: string
          email: string
          id: string
          image_url: string
          name: string
          updated_at?: string
        }
        Update: {
          bio?: string
          created_at?: string
          email?: string
          id?: string
          image_url?: string
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      tutorials: {
        Row: {
          author_id: string | null
          category: string
          content: string
          created_at: string
          description: string
          id: string
          image_hint: string
          image_url: string
          title: string
          updated_at: string
        }
        Insert: {
          author_id?: string | null
          category: string
          content: string
          created_at?: string
          description: string
          id?: string
          image_hint: string
          image_url: string
          title: string
          updated_at?: string
        }
        Update: {
          author_id?: string | null
          category?: string
          content?: string
          created_at?: string
          description?: string
          id?: string
          image_hint?: string
          image_url?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "tutorials_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// These types are now aliased from Prisma's generated types in data-service.ts
// but we keep the file for reference.
export type Experience = unknown;
export type PortfolioItem = unknown;
export type Profile = unknown;
export type Tutorial = unknown;
